name: Push to docker hub

on:
  push:
    branches: [ production ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ga-bot:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/ga-bot:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/ga-bot:buildcache,mode=max
          
